docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Intro: intro.md
    - "Quick Start": quick-start.md
    - Reference:
        - Definitions: definitions.md
        - "Instance Manager": instance-manager.md
        - Configuration: config.md
        - "Debugging and Complex Use Cases": debugging-and-complex-use-cases.md
site_name: laminas-di
site_description: laminas-di
repo_url: 'https://github.com/laminas/laminas-di'
